### ISSUE TITLE
Perfect Information shows wrong shooter

### ISSUE THREAD

**Issue by moben** [chrishayesmu/XCOM-LW-CommunityEdition#63] opened 2022-06-09 22:07 UTC
Perfect information says

> Alien Carbine uses Fire on Civilian

Instead of

> Floater uses Fire on Civilian

**Comment by chrishayesmu** [comment] 2022-06-09 22:53
I just noticed this today too. Zero idea what caused it but I was planning to take a look. Have you noticed that it's inconsistent? I think it said "Floater" when doing Suppression.

**Comment by chrishayesmu** [comment] 2022-06-10 06:37
Fixed in https://github.com/chrishayesmu/XCOM-LW-CommunityEdition/commit/3b7215417d30df6607a47a686a3cfb7a20a456a1

This was caused by a localization tag getting updated in the middle of building the Perfect Information string. That didn't happen in vanilla, but my rewrite of the hit/crit calculations made it possible.

**Closed by chrishayesmu** 2022-06-10 06:37 UTC
Labels: lwce-bug
