### ISSUE TITLE
Defense bonus from smoke does not count when running overwatch

### ISSUE THREAD

**Issue by Fjoggs** [chrishayesmu/XCOM-LW-CommunityEdition#96] opened 2024-01-13 15:05 UTC
I believe running an overwatch or a suppression inside a smoke does not grant you the 20/40 defense bonus if you're inside a smoke.

Sorry for the low quality issue report :sweat_smile:

**Comment by chrishayesmu** [comment] 2024-01-13 19:31
Duplicate of https://github.com/chrishayesmu/XCOM-LW-CommunityEdition/issues/27

**Closed** 2024-01-13 19:31 UTC
Labels: duplicate, base-game-bug
